### ISSUE TITLE
Not able to Deploy

### ISSUE THREAD

**Issue by hishammir** [blacklanternsecurity/writehat#110]
Hi there,
          i used docker-compose command , and i get 502 bad gateway error when i go to my http://vps-ip:80 and i get these errors too:
          
          writehat-nginx-1     | 2023/11/22 01:14:53 [error] 29#29: *5 connect() failed (113: No route to host) while connecting to upstream, client: 223.123.11.222, server: ~., request: "GET / HTTP/1.1", upstream: "uwsgi://172.20.0.4:8000", host: "3.88.132.138"
writehat-nginx-1     | 223.123.11.222 - - [22/Nov/2023:01:14:53 +0000] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
writehat-nginx-1     | 2023/11/22 01:14:56 [error] 29#29: *5 connect() failed (113: No route to host) while connecting to upstream, client: 223.123.11.222, server: ~., request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.20.0.4:8000", host: "3.88.132.138", referrer: "https://3.88.132.138/"
writehat-nginx-1     | 223.123.11.222 - - [22/Nov/2023:01:14:56 +0000] "GET /favicon.ico HTTP/1.1" 502 559 "https://3.88.132.138/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"

**Comment by thejohnbrown** [comment]
Did you add your IP to the allowed list in writehat.conf? https://github.com/blacklanternsecurity/writehat/blob/89f97e6fe655b9dcb4031066716243443412ef60/writehat/config/writehat.conf#L9

**Comment by spookey0188** [comment]
> Did you add your IP to the allowed list in writehat.conf?
> 
> https://github.com/blacklanternsecurity/writehat/blob/89f97e6fe655b9dcb4031066716243443412ef60/writehat/config/writehat.conf#L9

Obviously? It still gives the same error. "502 Bad Gateway"
