### ISSUE TITLE
Maintenance of this repository

### ISSUE THREAD

**Issue by thejohnbrown** [blacklanternsecurity/writehat#111]
Are there any plans to implement a regular schedule for releases of new versions of writehat? I can see the dev branch is over a 100 commits ahead of master and that includes lots of fixes for bugs which currently exist in the master branch. Also in terms of the future of the project, a few things were listed in the README as a future roadmap/potential features, are these being worked on either internally at black lantern security or within the open source community?

**Comment by TheTechromancer** [comment]
@TMDeal has secret plans.

**Comment by thejohnbrown** [comment]
Spill the beans @TMDeal 😄

**Comment by TMDeal** [comment]
Those secret plans are still in the works, but just know they are actively being worked on.
