### ISSUE TITLE
Page Header

### ISSUE THREAD

**Issue by Kleppp** [blacklanternsecurity/writehat#21]
Thank you for the amazing tool! 
Is there a consistent way to add a page header to a page template ?

**Comment by Kleppp** [comment]
The footer also sometimes does not show at all. I am certain I selected a template with a footer, which only has 2 simple lines. Any idea why that might happen ?

**Comment by kerrymilan** [comment]
Thanks Kleppp! 

Page headers aren't currently supported but adding them shouldn't be too involved. If you want to try implementing it yourself, you should be able to mirror what's being done with the footer:

 * __Template Form__ - Receive footer contents - [pageTemplate.py:128](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/lib/pageTemplate.py#L128)
 * __Template Model__ - Store footer contents - [pageTemplate.py:23](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/lib/pageTemplate.py#L23)
 * __Base Report__ - Insert footer into template - [report.py:393](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/lib/report.py#L393), [report.py:494](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/lib/report.py#L494)
 * __Base Template__ - Create placeholder HTML element - [reportBase.html:8](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/templates/reportTemplates/reportBase.html#L8)
 * __Report Stylesheet__ - Insert placeholder contents into page - [print.css:13](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/static/css/report/print.css#L13), [print.css:51](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/static/css/report/print.css#L51)
