### ISSUE TITLE
Subsections and Numbering

### ISSUE THREAD

**Issue by Wherekonshade** [blacklanternsecurity/writehat#22]
Hi,
first of all: thanks for your incredible work!

Adding subsections in a markdown with the normal ## does not add them to the Table Of Contents and they also do not get a Numbering like X.1 or X.2 etc.  Is this intended or is there another way to enable that ?

Kind regards :)

**Comment by TheTechromancer** [comment]
Great question! The way we decided to handle this is with "Container Components".  If you want to nest subsections like 1.1.2, 1.1.2, etc, you can place them inside a container component.

![image](https://user-images.githubusercontent.com/20261699/112649572-f24a8600-8e20-11eb-9fc2-c66806e976b1.png)
![image](https://user-images.githubusercontent.com/20261699/112649621-fb3b5780-8e20-11eb-87ef-b84cf6a5aa23.png)
