### ISSUE TITLE
Background Image Dimensions

### ISSUE THREAD

**Issue by Wherekonshade** [blacklanternsecurity/writehat#25]
Hi,
I would like the background image to span over the entire page. I feel like this should be a oneliner, but I can't seem to find the respective parameter.
Any help would be appreciated :)

Thank you!

**Comment by cclauss** [comment]
Can you please provide a link to the file in question?

**Comment by Wherekonshade** [comment]
> Can you please provide a link to the file in question?

I think the main change should be done in [print.css](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/static/css/report/print.css)
but I think the margin/dimension might be affected by [pageTemplate.py](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/lib/pageTemplate.py) as well.

**Comment by Wherekonshade** [comment]
The main change had to be done in print.css. The main problem was my little understanding of how the components interact and how the margin parameter works. If anyone else has this issue I would be happy to explain it in more detail (Wherekonshade@web.de).
