### ISSUE TITLE
Findings in TOC

### ISSUE THREAD

**Issue by Wherekonshade** [blacklanternsecurity/writehat#29]
Hi :)
Imho every Finding should automatically be a children of Findings in the TOC( Like this:
3.Findings
&ensp; 3.1 Finding 1
&ensp; 3.2 Finding 2
 &ensp; 3.3 Finding 3
)
, so one gets an overview of the findings even by just looking at the TOC.

Could you give me a hint on how I could implement this in the fastest & easiest way ?

Thank you and best regards

**Comment by Wherekonshade** [comment]
I tought a simple for loop in the TableOfContents.html like this:
```
{% if component.name == "Findings" %}
    {% for finding in fgroup %}
         {% if not report.finding_uuids or finding.id in report.finding_uuids %}
                  <span style='margin-left: {{ component.level }}em;' class="toc-item">{{ finding.name }}</span>
                  <span class="toc-dots"></span>
                  <span class="toc-pagenumber" target-component='#component_{{ finding.id }}'></span>
           {% endif %}
     {% endfor %}
{% endif %}
```
 should do the trick but somehow this does not even show anything in the TOC :/

**Comment by TheTechromancer** [comment]
Hmm, you may have better luck editing `writehat/components/TableOfContents.py` and modifying the `toc_components` variable directly.

![image](https://user-images.githubusercontent.com/20261699/126378751-ef71f4c7-afb9-41e9-ae03-56b92b4d67cf.png)

**Comment by Wherekonshade** [comment]
This worked. Thank you :)
