### ISSUE TITLE
Selenium docker not working with attached docker-compose

### ISSUE THREAD

**Issue by craftbyte** [blacklanternsecurity/writehat#3]
With the attached docker-compose the Selenium docker throws the following when trying to generate a PDF report. This could be my config, but just wanted to check.

```
chrome_1    | 2020-12-02 17:31:50,549 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome_1    | 2020-12-02 17:31:50,556 INFO supervisord started with pid 8
chrome_1    | 2020-12-02 17:31:51,560 INFO spawned: 'xvfb' with pid 11
chrome_1    | 2020-12-02 17:31:51,563 INFO spawned: 'selenium-standalone' with pid 12
chrome_1    | 2020-12-02 17:31:52,564 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1    | 2020-12-02 17:31:52,564 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1    | 17:32:22.356 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
chrome_1    | 17:32:24.024 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
chrome_1    | 2020-12-02 17:32:24.932:INFO::main: Logging initialized @28990ms to org.seleniumhq.jetty9.util.log.StdErrLog
chrome_1    | 17:32:28.782 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
chrome_1    | 17:32:30.011 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
chrome_1    | 17:34:40.803 INFO [ActiveSessionFactory.apply] - Capabilities are: {
chrome_1    |   "browserName": "chrome",
chrome_1    |   "goog:chromeOptions": {
chrome_1    |     "extensions": [
chrome_1    |     ],
chrome_1    |     "args": [
chrome_1    |       "--disable-extensions",
chrome_1    |       "--headless",
chrome_1    |       "--no-sandbox",
chrome_1    |       "--disable-dev-shm-usage",
chrome_1    |       "--ignore-certificate-errors",
chrome_1    |       "--allow-running-insecure-content"
chrome_1    |     ]
chrome_1    |   },
chrome_1    |   "version": ""
chrome_1    | }
chrome_1    | 17:34:40.806 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
chrome_1    | Starting ChromeDriver 87.0.4280.20 (c99e81631faa0b2a448e658c0dbd8311fb04ddbd-refs/branch-heads/4280@{#355}) on port 27724
chrome_1    | Only local connections are allowed.
chrome_1    | Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
chrome_1    | ChromeDri[1v6e0r6 9w3a0s4 8s1t.a0r4t2e]d[ SsEuVcEcReEs]s:f ublilnyd.(
chrome_1    | ) failed: Cannot assign requested address (99)
chrome_1    | 17:34:43.136 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
chrome_1    | 17:34:43.175 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session db65253291c94b8585354b73ef81c881 (org.openqa.selenium.chrome.ChromeDriverService)
```

**Comment by liquidsec** [comment]
Could you provide your OS version and docker/docker-compose versions?

**Comment by craftbyte** [comment]
Ubuntu 18.04.5 LTS
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.27.4, build 40524192

I should add that when I run the following and exec into the container Chrome seems to start ok:
`docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-20201119`

**Comment by kerrymilan** [comment]
I'm having a hard time replicating this one -- it seems odd that it would work when you're forwarding the port, but not when you're exposing it internally. 

 * Is anything else running on your host's port 4444? 
 * Are you running Docker with IPv6 enabled? 
 * Is there anything at the host level that would be dropping `cap_net_bind_service`?

**Comment by craftbyte** [comment]
I am running Docker with IPv6 enabled (was changed after reading issues on this topic). Port 4444 seems to work OK. The problem appears to be in the Chrome process binding to a port that the Selenium engine connects to (so a completely local operation).

**Comment by keesj** [comment]
> failed: Cannot assign requested address (99)

I have the same problem when running and do not see what is obviously wrong in my setup. I am trying the setup from /opt using systemd as documented.  I do not see anything obvious in the kernel messages. 

root@dude:/var/log# apt-cache policy docker.io
docker.io:
  Installed: (none)
  Candidate: 19.03.13-0ubuntu3.1
  Version table:
     19.03.13-0ubuntu3.1 500
        500 http://nl.archive.ubuntu.com/ubuntu groovy-updates/universe amd64 Packages
     19.03.13-0ubuntu3 500
        500 http://nl.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
root@dude:/var/log# uname -a
Linux dude 5.8.0-43-generic #49-Ubuntu SMP Fri Feb 5 03:01:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@dude:/var/log# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

**Comment by keesj** [comment]
It appears the problem on my side was not related to this initial message. The message is quite confusing and to pass the correct argument to chromedriver it was nesesary to add an option that is passed to the selenuim jvm. e.g. adding 
+    environment:
+      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
in the docker-compose.
