### ISSUE TITLE
create Reporting Templates error

### ISSUE THREAD

**Issue by haiopaii** [blacklanternsecurity/writehat#30]
Hey guys,
I´ve set WH up as written in the README.
When trying to create a new Report Template (btw. the first), we get an Server Error 500.
Also the Admin-Tools link is dead (not found). Any suggestions?

Fresh installed WH on debian 10.9

`writehat_1  | 2021-04-09 14:10:17 - DEBUG   - views.py: 1260 - enagagementsList (GET) called
writehat_1  | [pid: 35|app: 0|req: 7/21] 172.30.0.132 () {46 vars in 843 bytes} [Fri Apr  9 14:10:17 2021] GET /engagements => generated 10639 bytes in 13 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
writehat_1  | [pid: 33|app: 0|req: 9/22] 172.30.0.132 () {48 vars in 879 bytes} [Fri Apr  9 14:10:17 2021] GET /validation/whitelists => generated 745 bytes in 7 msecs (HTTP/1.1 200) 6 headers in 172 bytes (1 switches on core 0)
writehat_1  | [pid: 35|app: 0|req: 8/23] 172.30.0.132 () {46 vars in 838 bytes} [Fri Apr  9 14:13:30 2021] GET /templates => generated 12763 bytes in 47 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
writehat_1  | [pid: 35|app: 0|req: 9/24] 172.30.0.132 () {48 vars in 877 bytes} [Fri Apr  9 14:13:31 2021] GET /validation/whitelists => generated 745 bytes in 7 msecs (HTTP/1.1 200) 6 headers in 172 bytes (1 switches on core 0)
writehat_1  | 2021-04-09 14:13:46 - DEBUG   - views.py: 1726 - templateNew called;
writehat_1  | 2021-04-09 14:13:46 - ERROR   - log.py:  224 - Internal Server Error: /templates/new
writehat_1  | Traceback (most recent call last):
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
writehat_1  |     response = get_response(request)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
writehat_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/http.py", line 40, in inner
writehat_1  |     return func(request, *args, **kwargs)
writehat_1  |   File "./writehat/views.py", line 1728, in templateNew
writehat_1  |     return render(
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render
writehat_1  |     content = loader.render_to_string(template_name, context, request, using=using)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 62, in render_to_string
writehat_1  |     return template.render(context, request)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 61, in render
writehat_1  |     return self.template.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 170, in render
writehat_1  |     return self._render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 162, in _render
writehat_1  |     return self.nodelist.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
writehat_1  |     bit = node.render_annotated(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
writehat_1  |     return self.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 150, in render
writehat_1  |     return compiled_parent._render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 162, in _render
writehat_1  |     return self.nodelist.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
writehat_1  |     bit = node.render_annotated(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
writehat_1  |     return self.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 62, in render
writehat_1  |     result = block.nodelist.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
writehat_1  |     bit = node.render_annotated(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
writehat_1  |     return self.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 195, in render
writehat_1  |     return template.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 172, in render
writehat_1  |     return self._render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 162, in _render
writehat_1  |     return self.nodelist.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
writehat_1  |     bit = node.render_annotated(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
writehat_1  |     return self.render(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 988, in render
writehat_1  |     output = self.filter_expression.resolve(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 671, in resolve
writehat_1  |     obj = self.var.resolve(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 796, in resolve
writehat_1  |     value = self._resolve_lookup(context)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 858, in _resolve_lookup
writehat_1  |     current = current()
writehat_1  |   File "./writehat/lib/report.py", line 67, in __init__
writehat_1  |     super().__init__(*args, **kwargs)
writehat_1  |   File "./writehat/models.py", line 63, in __init__
writehat_1  |     super().__init__(*args, **kwargs)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 413, in __init__
writehat_1  |     raise TypeError('Abstract models cannot be instantiated.')
writehat_1  | TypeError: Abstract models cannot be instantiated.
writehat_1  | [pid: 35|app: 0|req: 10/25] 172.30.0.132 () {46 vars in 844 bytes} [Fri Apr  9 14:13:46 2021] GET /templates/new => generated 145 bytes in 15 msecs (HTTP/1.1 500) 6 headers in 184 bytes (1 switches on core 0)
`
![grafik](https://user-images.githubusercontent.com/36101628/114178599-3f107f80-993e-11eb-96d2-f479628ceb34.png)
![grafik](https://user-images.githubusercontent.com/36101628/114178673-53ed1300-993e-11eb-9975-e9c2f4b393a3.png)

**Comment by blockanz** [comment]
I also have the same issue.

**Comment by ping-of-death** [comment]
Same issue here. 
I tried on Kali and Ubuntu.

**Comment by resulkucar** [comment]
I'm also having the same issue. I tried messing around with the report template directory but couldn't find anything to fix it.

**Comment by parad0x-0xff** [comment]
I'm having the same problem, I tried change permissions. But no luck

**Comment by TheTechromancer** [comment]
Looks like this was an issue with Django 3.2 specifically. Downgrading to 3.1 fixes it. Version is now pinned in requirements.txt. b5cd06d52c4ca40e1c01ab78942e44fe57da6697
