### ISSUE TITLE
Package locales has no installation canidate

### ISSUE THREAD

**Issue by emilyanncr** [blacklanternsecurity/writehat#35]
I am attempting to install writehat on my Kali Virtual Machine version 5.10.0-kali9-amd64 (the most updated version).  After changing the passwords etc, upon running docker-compose up I get an error about  packages locales and locales-all not being available but referred to by another package.  Both packages are already installed on my system however.  See attached screenshots.  Thanks for the assistance!

![info](https://user-images.githubusercontent.com/8577656/124830890-5f48de00-df2f-11eb-8798-6a1e2b014cea.png)

![locales installed](https://user-images.githubusercontent.com/8577656/124831007-84d5e780-df2f-11eb-9d9a-d442fd365f76.png)

**Comment by TheTechromancer** [comment]
Docker filesystems are separate from your OS. It's possible that your cached Ubuntu image is either outdated or corrupt.

First ensure you have the latest versions of docker and docker-compose (and that they're installed from the official sources, NOT from the dreadful Kali repos), then try building the image again with `docker-compose build --no-cache writehat`.

**Comment by emilyanncr** [comment]
An outdated or corrupt image? hmmmm interesting. I'm having issues building other things as well, perhaps this is the cause.  I'm going to have to dig deeper on this.  Thanks for your assistance!
