### ISSUE TITLE
Cannot create report template with newest version of MongoDB

### ISSUE THREAD

**Issue by filipholec** [blacklanternsecurity/writehat#42]
Hi, I tried installing writehat today from docker-compose.yml file and I've encountered several issues. The main one was that I was not able to create report template (call failed with http code 500).

Error from docker logs: `TypeError: 'Collection' object is not callable. If you meant to call the 'update' method on a 'Collection' object it is failing because no such method exists.`

Once I've pulled mongo version 4.4 (or similar) and downgraded pymongo module (in requirements.txt) to version 3.11, the report template started working. Maybe you can lock versions of components to specific ones instead of the latest one.

My CPU is Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (Coffee Lake) which is a couple of generations newer than Sandy Bridge, that Mongo v5 should support.

**Comment by TheTechromancer** [comment]
Thanks for pointing this out. Mongo version is now pinned in `docker-compose.yml`. 65a07d60b68b7e26dfc2071a86d9fe22c53b50b8 9d96575dc4339e70aab46ca62b2e09b8d6d404cf
