### ISSUE TITLE
/usr/bin/env: ‘python\r’: No such file or directory

### ISSUE THREAD

**Issue by bdno86** [blacklanternsecurity/writehat#50]
When running docker-compose up on the writehat root dir the following error ends up being produced causing the writehat container to exit:

```
writehat_writehat_1 exited with code 127
writehat_1  | /usr/bin/env: ‘python\r’: No such file or directory
````
This seems to be caused by how EOL's are encoded. One fix would be to find the file causing this and doing `:set ff=unix` in vim.

A working solution is to run this in the root dir:

```git
git config core.autocrlf false
git rm --cached -r .         # Don’t forget the dot at the end
git reset --hard
```

It would be nice to have a permanent solution baked into the repo though.

**Comment by bradbm** [comment]
Spent some time playing whack-a-mole changing individual file endings before this. This option is the easier fix for sure.

**Comment by TheTechromancer** [comment]
Unix newlines are now enforced. c4713097e77a7e76a7c265d8b715e48de2fecbde
