### ISSUE TITLE
Unable to remove uploaded figures from finding

### ISSUE THREAD

**Issue by Foxi352** [blacklanternsecurity/writehat#6]
When you add figures to a finding using the "Figures" button on top-right you can't delete them later on.
I added 3 figures like that and now want to remove them again. I click the red "X" on every figure and they disappear from the list.
After saving and reloading, or going back and reentering the finding, the figures are all there again.

Now i have 3 figures printing after my finding which i am unable to remove.

Edit: I am testing on the "quick and dirty" docker-compose up with all default settings

**Comment by kerrymilan** [comment]
It took a little while to replicate this one but I think I know what's going on. When you delete the figures, are you removing all 3 at once? If so, does deleting one or two at a time change anything?

**Comment by Foxi352** [comment]
Yes i tried removing all 3 at once.
Here is what i tried now based on your reply:

- Removed only 1, saved: Got 2 green messages "Successfully saved finding" and "Successfully saved figures metadata" (can't remember exact wording)
- Went back and entered finding again: Only 2/3 figures left ! That worked.
- Removed again only 1 of the two figures left. Same result: 2 green messages on saving and worked.
- Went back and entered finding again: Only 1/3 figures left. That worked too.

But i was then unable to delete the last figure. I Can remove it but when i click save i only have the one gree message about saving the finding. No mention about figure metadata. When i go back and reenter the finding again that last figure reappears. No way to get rid of it.

Hope that helps ....

**Comment by kerrymilan** [comment]
Thanks, that confirms my suspicions: the issue arises when deleting the last figure in a finding because the call to 'update figure metadata' only fires if the list is not empty. I've pushed a fix for this internally; we'll publish it once the team has had a chance to review. Thanks again for taking the time to dig in to this.

**Comment by Foxi352** [comment]
Thank you for your quick reaction. Do you think that you will be able to publish this during this week ?
I used Writehat to write an pentest exam report for my master studies, and i have to submit it starting next week.

If not, can you maybe tell me what to modify to fix it ? Or maybe send a diff ?

Thanks a lot.

**Comment by kerrymilan** [comment]
Yesterday's update includes a fix that should address this issue. Can you pull it down and verify? 

All changes relating to this bug are in `writehat/static/js/findingEdit.js`.

**Comment by Foxi352** [comment]
Yes !

I confirm this working. Thank you for your prompt fix !

Serge
