### ISSUE TITLE
PDF report generation only works once

### ISSUE THREAD

**Issue by n0mead** [blacklanternsecurity/writehat#88]
Hello all,

I had the problem that I can generate a PDF only once. After that new generation requests will result in a timeout. I had to run `docker-compose restart` again and again to be able to generate more PDF reports. This was also the case for very small reports (generation time less than 20 seconds).

After some debugging I noticed that the problem is somehow related to the Chrome Selenium WebDriver sessions. The session is not closed after the first PDF generation. So for the next PDF generation, the driver can't connect.

I was able to fix the problem by replacing the `browser.close()` with  `browser.quit()` in `views.py`.
I don't know, if this will cause any other issues. For now it seems to work fine.

**Comment by r3nt0n** [comment]
Same issue here, @n0mead thanks for sharing the workaround!

**Comment by TMDeal** [comment]
ya, this was a fun issue to find and debug. This exact fix has actually already been commited to the [github-dev branch](https://github.com/blacklanternsecurity/writehat/tree/github-dev). Nice catch.
