### ISSUE TITLE
Network error when downloading PDF

### ISSUE THREAD

**Issue by sdcampbell** [blacklanternsecurity/writehat#9]
When I generate a PDF report, it opens a new tab and displays the PDF, but when I try to download the PDF I get a network error. I tried using Chrome and Edge browsers and had the same result. To ensure it wasn't actually a network error, I downloaded a report from our Serpico reporting application without error. I have included a screenshot which shows successful download on the left side from Serpico. The three failures to the right of that are from WriteHat.

![WriteHat Network Error](https://user-images.githubusercontent.com/10532268/104733545-dc2b9580-570c-11eb-82b3-acc2096e62de.png)

**Comment by sdcampbell** [comment]
The first time this happened, we went through the installation instructions under "Deploying WriteHat (The right way)". Over the past weekend I needed a quick pentest report and used Writehat from Docker (The quick and easy way for testing) and had the same issue. The download failed as it did before due to network error, but I worked around it by printing to PDF in Chrome browser. Great reporting app, keep up the great work!

**Comment by sdcampbell** [comment]
Also, when I tried to download from Docker and got the error, it was running locally whereas the first time I submitted this bug report it was running from a system over the network.

**Comment by TheTechromancer** [comment]
Reports (especially big ones) can take a long time to render.  You might want to try increasing the timeout values in the nginx config.

![image](https://user-images.githubusercontent.com/20261699/108733528-937dae00-74fc-11eb-99d2-28401cf1f247.png)

**Comment by sdcampbell** [comment]
I'll give that a try, but want you to know that this happens even on very short reports with 3 to 4 findings I created as a demo of the application.

**Comment by Wherekonshade** [comment]
I just encountered this issue as well. For me the problem was, that I had created too many reports. Closing them and recreating just a single one fixed it. 
Just in case anyone encounters this issue :)

**Comment by MrMisconception** [comment]
> Reports (especially big ones) can take a long time to render. You might want to try increasing the timeout values in the nginx config.
> 
> ![image](https://user-images.githubusercontent.com/20261699/108733528-937dae00-74fc-11eb-99d2-28401cf1f247.png)

The file @TheTechromancer is talking about is [writehat/writehat/config/nginx.conf](https://github.com/blacklanternsecurity/writehat/blob/master/writehat/config/nginx.conf).
I increased the timeout to 3000s and it worked for me.

**Comment by sdcampbell** [comment]
In my case my report had three findings so it wasn't large. The report was simple and only being used to evaluate the application to replace Serpico. Regardless, I've moved on from Writehat and no longer use it.
