### ISSUE TITLE
Unable to add "Finding Group"; no options available from drop down menu.

### ISSUE THREAD

**Issue by Business1sg00d** [blacklanternsecurity/writehat#92]
I have a finding under Category "External Network PenTest(Active Directory)":
![image](https://github.com/blacklanternsecurity/writehat/assets/112768445/381fa2bd-e38f-486d-a192-b85a9e53f600)

I create a report, add the "Findings" component, then I edit "Findings". Here I attempt to locate "External Network PenTest(Active Directory)":
![image](https://github.com/blacklanternsecurity/writehat/assets/112768445/2f214729-6fe6-4c35-abc5-aca27ec15921)

How exactly do I create/add a Finding Group to the Findings component?

**Comment by thejohnbrown** [comment]
You're trying to add a category from your Findings Database which you can't do. You need to create a finding group inside your engagement (the section where you create reports, etc.) and then that will show up as a Finding Group to include in your report.

**Comment by thejohnbrown** [comment]
@Business1sg00d Did this sort the issue for you?

**Comment by Business1sg00d** [comment]
Yes it did. Closing issue now. Thank you.
