### ISSUE TITLE
Bug: Additional meta tags

### ISSUE THREAD

**Issue by thejohnbrown** [blacklanternsecurity/writehat#96]
I've found a bug in the PR I made for the additional meta tags. Basically when trying to get counts for a specific finding group, it will retrieve a different finding groups totals. I've identified the issue and will look at making a fix this week.

**Comment by TMDeal** [comment]
this fix has been merged into github-dev from [https://github.com/blacklanternsecurity/writehat/pull/97](https://github.com/blacklanternsecurity/writehat/pull/97)
